[game]
name = "Summon Night: Craft Sword Monogatari - Hajimari no Ishi"
short_name = "swordcraft_story_3"
default_region = "japan"

[bios]
path = "gbarecomp/bios/gba_bios.bin"
sha1 = "300c20df6731a33952ded8c436f7f186d25d3492"

[rom]
path = "roms/swordcraft3_jp.gba"
sha1 = "3f5253fcf57e07ce52472bd29a61d16b98a12376"
crc32 = "0x12AFAE5D"

[recompiler]
entry_point = "0x08000000"
seeds = "symbols/imported_symbols.tsv"
boundaries = "symbols/function_boundaries.tsv"
out_dir = "generated"
strict = false

[save]
type = "eeprom"
size = "0x2000"

[runtime]
debug_port = 19853
window_title = "Summon Night: Swordcraft Story 3"

[video]
screen = "frontlit"

[audio]
shadow = false
