# Keep headers, import library and shipped DLL on the same project-owned SDK.
# This does not update the machine's compiler/SDL installation or other ports.
if(WIN32 AND MINGW AND NOT GBARECOMP_STATIC_RELEASE)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/../packaging/sdl2.json" sc3_sdl_pin)
    string(JSON sc3_sdl_version GET "${sc3_sdl_pin}" version)
    string(JSON sc3_sdl_directory GET "${sc3_sdl_pin}" directory)
    string(JSON sc3_sdl_hash GET "${sc3_sdl_pin}" dll_sha256)
    get_filename_component(sc3_owner "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
    set(SWORDCRAFT3_SDL2_ROOT
        "${sc3_owner}/.tooling/sdl2-${sc3_sdl_version}/${sc3_sdl_directory}"
        CACHE PATH "Verified SDL2 MinGW SDK (tools/setup_sdl2.ps1)")
    set(sc3_sdl_x64 "${SWORDCRAFT3_SDL2_ROOT}/x86_64-w64-mingw32")
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "The pinned portable SDL2 SDK requires a 64-bit build")
    endif()
    foreach(sc3_sdl_file bin/SDL2.dll include/SDL2/SDL.h lib/libSDL2.dll.a)
        if(NOT EXISTS "${sc3_sdl_x64}/${sc3_sdl_file}")
            message(FATAL_ERROR "Missing SDL2 ${sc3_sdl_version}; run tools/setup_sdl2.ps1")
        endif()
    endforeach()
    file(SHA256 "${sc3_sdl_x64}/bin/SDL2.dll" sc3_sdl_actual)
    if(NOT sc3_sdl_actual STREQUAL sc3_sdl_hash)
        message(FATAL_ERROR "Pinned SDL2 DLL checksum mismatch")
    endif()
    set(SDL2_DIR "${sc3_sdl_x64}/lib/cmake/SDL2" CACHE PATH "Pinned SDL2 config" FORCE)
    set(SDL2_INCLUDE_DIR "${sc3_sdl_x64}/include/SDL2" CACHE PATH "Pinned SDL2 headers" FORCE)
    set(SDL2_LIBRARY "${sc3_sdl_x64}/lib/libSDL2.dll.a" CACHE FILEPATH "Pinned SDL2 import library" FORCE)
    set(GBARECOMP_SDL2_RUNTIME_DLL "${sc3_sdl_x64}/bin/SDL2.dll" CACHE FILEPATH "Pinned SDL2 runtime" FORCE)
endif()
